# FEATURE ENGINEERING

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [13]:
data_df =pd.read_csv('autompg.csv')
data_df

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [14]:
data_df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [15]:
data_df.shape


(398, 9)

In [16]:
data_df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [17]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [25]:
data_df.info('exclude=[object]')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [31]:
X =  data_df.iloc[:,[2,4]]
y=   data_df.iloc[:, 5]

In [35]:
data_df.head(2)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [33]:
X.head()

displacement  weight
0         307.0    3504
1         350.0    3693
2         318.0    3436
3         304.0    3433
4         302.0    3449

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [40]:
X_train, X_test, y_test, y_train = train_test_split(X,y, random_state=40)

In [42]:
X_train.head()

displacement  weight
256         225.0    3430
295          98.0    1915
100         250.0    3021
253         200.0    3155
369         112.0    2395

In [43]:
scaler = StandardScaler().fit(X_train)
scaler 

StandardScaler()

In [45]:
scaler.mean_


array([ 193.29362416, 2978.66107383])

In [48]:
scaler.scale_

array([102.4388434 , 827.30502634])

In [50]:
scaler.transform(X_test)

array([[-1.11572545, -1.22767425],
       [ 0.30951517,  0.76675338],
       [-0.70572472, -0.56528252],
       [-1.12548737, -1.20108188],
       [-0.75453433, -0.99196916],
       [ 0.37784862, -0.07815869],
       [-0.75453433, -0.91702703],
       [-0.99858238, -1.2373442 ],
       [ 1.85189885,  2.38888785],
       [-0.99858238, -1.43074324],
       [ 1.08070701,  0.54917946],
       [-0.36405745, -0.47583547],
       [-0.94001085, -1.24338792],
       [-0.71548664, -0.98955167],
       [ 2.01785152,  2.13626035],
       [-0.5202482 , -0.41056329],
       [ 1.08070701,  0.83806928],
       [ 1.06118316,  0.56851936],
       [ 1.10999277,  1.68902507],
       [-0.94001085, -1.02581399],
       [ 1.06118316,  2.005716  ],
       [-0.51048628,  0.25545466],
       [-0.6081055 , -0.17969318],
       [ 1.53951734,  1.39046529],
       [-0.94001085, -0.97625549],
       [-0.99858238, -1.20108188],
       [ 0.63165859,  0.90817643],
       [ 1.9202323 ,  1.05322571],
       [ 1.52975542,

In [49]:
scaler.transform(X_train)

array([[ 3.09515168e-01,  5.45553226e-01],
       [-9.30248927e-01, -1.28569396e+00],
       [ 5.53563218e-01,  5.11769237e-02],
       [ 6.54671179e-02,  2.13148622e-01],
       [-7.93582019e-01, -7.05496830e-01],
       [-6.95962799e-01, -8.08240072e-01],
       [-4.81200515e-01, -3.79135946e-01],
       [-1.19382082e+00, -1.45733561e+00],
       [ 1.21737392e+00,  1.40376148e+00],
       [-8.61915473e-01, -1.00163911e+00],
       [ 3.77848622e-01,  3.73911576e-01],
       [ 7.19515893e-01,  7.57083429e-01],
       [-8.42391629e-01, -6.63190790e-01],
       [ 1.21737392e+00,  1.46419868e+00],
       [ 6.70706282e-01,  4.39244596e-02],
       [-7.64296253e-01, -3.44082370e-01],
       [ 6.54671179e-02, -1.65127412e-02],
       [ 2.30094726e+00,  2.38526162e+00],
       [-9.40010849e-01, -9.55706842e-01],
       [ 1.06118316e+00,  2.30071038e-01],
       [ 1.09046893e+00,  1.08948803e+00],
       [ 3.68086700e-01,  4.85116025e-01],
       [-6.95962799e-01, -9.17027033e-01],
       [-1.

In [52]:
X_train_scaled = scaler.transform(X_train)

In [53]:
X_train_scaled.mean(axis=0)

array([-9.53748639e-17, -2.14593444e-16])

In [54]:
X_train_scaled.std(axis=0)

array([1., 1.])