In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [6]:
df = pd.read_csv('autompg.csv')
df.head(2)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object 
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB


In [9]:
df.dtypes


mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [10]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [11]:
df.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  \
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin         car name  
393          82       1  ford mustang gl  
394          82       2        vw pickup  
395          82       1    dodge rampage  
396          82       1      ford ranger  
397          82       1       chevy s-10

In [12]:
from sklearn.model_selection import train_test_split

In [14]:
X = df.iloc[:,[2,4]]
y= df.iloc[:,5]

In [16]:
X.head(3)

displacement  weight
0         307.0    3504
1         350.0    3693
2         318.0    3436

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=40)

In [19]:
X_train

displacement  weight
256         225.0    3430
295          98.0    1915
100         250.0    3021
253         200.0    3155
369         112.0    2395
..            ...     ...
306         173.0    2595
165         262.0    3221
7           440.0    4312
219         122.0    2300
326          90.0    2335

[298 rows x 2 columns]

In [20]:
from sklearn.preprocessing import StandardScaler

In [22]:
# scaling and fitting of the train model
scaler = StandardScaler().fit(X_train)
scaler

StandardScaler()

In [23]:
scaler.scale_

array([102.4388434 , 827.30502634])

In [24]:
scaler.mean_

array([ 193.29362416, 2978.66107383])

In [26]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [27]:
scaler.transform(X_test)

array([[-1.11572545, -1.22767425],
       [ 0.30951517,  0.76675338],
       [-0.70572472, -0.56528252],
       [-1.12548737, -1.20108188],
       [-0.75453433, -0.99196916],
       [ 0.37784862, -0.07815869],
       [-0.75453433, -0.91702703],
       [-0.99858238, -1.2373442 ],
       [ 1.85189885,  2.38888785],
       [-0.99858238, -1.43074324],
       [ 1.08070701,  0.54917946],
       [-0.36405745, -0.47583547],
       [-0.94001085, -1.24338792],
       [-0.71548664, -0.98955167],
       [ 2.01785152,  2.13626035],
       [-0.5202482 , -0.41056329],
       [ 1.08070701,  0.83806928],
       [ 1.06118316,  0.56851936],
       [ 1.10999277,  1.68902507],
       [-0.94001085, -1.02581399],
       [ 1.06118316,  2.005716  ],
       [-0.51048628,  0.25545466],
       [-0.6081055 , -0.17969318],
       [ 1.53951734,  1.39046529],
       [-0.94001085, -0.97625549],
       [-0.99858238, -1.20108188],
       [ 0.63165859,  0.90817643],
       [ 1.9202323 ,  1.05322571],
       [ 1.52975542,